version: '3.8'
services:
  db:
    image: postgres:14.0-alpine
    env_file: ./docker.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    tty: true
  api:
    env_file: ./docker.env
    build:
      context: .
      dockerfile: ./api/Dockerfile
    volumes:
      - './api:/app:cached'
    ports:
      - "8080:8080"
      - "5678:5678"
    depends_on:
      - db
    tty: true
    stdin_open: true
volumes:
  pgdata:
  node_modules: