# Generated by Django 3.2.16 on 2023-02-23 04:27

import uuid

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="名前")),
                (
                    "email",
                    models.EmailField(
                        max_length=256, unique=True, verbose_name="メールアドレス"
                    ),
                ),
                (
                    "new_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="変更確認前のメールアドレス",
                    ),
                ),
                ("password", models.CharField(max_length=100, verbose_name="パスワード")),
                ("miss_count", models.IntegerField(default=0, verbose_name="ログイン失敗回数")),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.Group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.Permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "ユーザー",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="JobAds",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("publication_start", models.DateField(verbose_name="公開日")),
                ("publication_end", models.DateField(verbose_name="掲載終了日")),
                ("title", models.TextField(verbose_name="タイトル")),
                ("contents", models.TextField(verbose_name="内容")),
                ("views", models.PositiveIntegerField(default=0, verbose_name="閲覧数")),
                ("cost", models.PositiveIntegerField(verbose_name="単発掲載費用")),
            ],
            options={
                "verbose_name": "求人広告",
            },
        ),
        migrations.CreateModel(
            name="JobMaster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_offer_name",
                    models.CharField(max_length=100, verbose_name="求人媒体"),
                ),
                ("subscription_cost", models.PositiveIntegerField(verbose_name="月額")),
                ("detail", models.TextField(verbose_name="特筆事項")),
            ],
            options={
                "verbose_name": "求人媒体",
            },
        ),
        migrations.CreateModel(
            name="JobSeeker",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, null=True, verbose_name="名"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, null=True, verbose_name="姓"),
                ),
                (
                    "first_name_kana",
                    models.CharField(max_length=100, null=True, verbose_name="メイ"),
                ),
                (
                    "last_name_kana",
                    models.CharField(max_length=100, null=True, verbose_name="セイ"),
                ),
                (
                    "mail",
                    models.EmailField(
                        max_length=256, null=True, unique=True, verbose_name="メールアドレス"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("men", "男性"), ("woman", "女性"), ("unknown", "不明")],
                        max_length=16,
                        verbose_name="性別",
                    ),
                ),
                ("career", models.TextField(verbose_name="経歴")),
                ("memo", models.JSONField(blank=True, default=list, verbose_name="メモ")),
                (
                    "assign",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assign",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="担当者",
                    ),
                ),
                (
                    "job_ads",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="job_ads",
                        to="v1.jobads",
                        verbose_name="求人広告記事",
                    ),
                ),
            ],
            options={
                "verbose_name": "求職者",
            },
        ),
        migrations.CreateModel(
            name="Progress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "progress",
                    models.CharField(
                        choices=[
                            ("apply", "応募"),
                            ("casual_interview", "カジュアル面談"),
                            ("first_interview", "一次面接"),
                            ("second_interview", "二次面接"),
                            ("third_interview", "三次面接"),
                            ("final_interview", "最終面接"),
                            ("unofficial_offer", "内定"),
                            ("joining_the_company", "入社"),
                            ("follow", "フォロー"),
                        ],
                        max_length=100,
                        verbose_name="進捗",
                    ),
                ),
                ("implementation_at", models.DateField(verbose_name="実施日")),
                ("is_implementation", models.BooleanField(verbose_name="実施")),
                ("is_result", models.BooleanField(verbose_name="結果")),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="author",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "job_seeker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_seeker",
                        to="v1.jobseeker",
                        verbose_name="求職者",
                    ),
                ),
            ],
            options={
                "verbose_name": "進捗情報",
            },
        ),
        migrations.AddField(
            model_name="jobads",
            name="job_master",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="job_ads",
                to="v1.jobmaster",
                verbose_name="求人媒体",
            ),
        ),
    ]
